import { imagesFor } from "./reef-images";
import type { ReefSite } from "./types";

const commonPreparation = [
  "Confirm current sea, weather and site conditions with a licensed dive operator.",
  "Bring your certification details and follow the operator's equipment and safety guidance.",
];

const sources = {
  Perhentian: { label: "PADI — Diving the Perhentian Islands", url: "https://blog.padi.com/seeking-adventure-in-malaysias-perhentian-islands/" },
  Redang: { label: "Tourism Malaysia — Dive in Paradise", url: "https://storage.ebrochures.malaysia.travel/storage/IDB_PDF_DIP_EN.pdf" },
  Tioman: { label: "PADI — Diving in Tioman Island", url: "https://www.padi.com/diving-in/malaysia/tioman-island/" },
} as const;

type ProfileSpec = {
  id: string;
  backendDiveSiteId: number;
  name: string;
  island: "Perhentian" | "Redang" | "Tioman";
  publicAreaLabel: string;
  position: [number, number];
  introduction: string;
  habitat: string;
  marineLife: string;
  reason: string;
  level: "Beginner" | "Intermediate" | "Experienced";
  preparation?: string[];
  source?: { label: string; url: string };
};

const profileSpecs: ProfileSpec[] = [
  { id: "perhentian-batu-nisan", backendDiveSiteId: 17, name: "Batu Nisan", island: "Perhentian", publicAreaLabel: "Perhentian Islands", position: [5.903, 102.721], introduction: "Batu Nisan is a shallow Perhentian house-reef dive that PADI lists for both shore and boat entry, with a maximum depth of about 12 metres.", habitat: "A shallow ocean reef close to Long Beach provides an accessible setting for a relaxed dive.", marineLife: "PADI's Perhentian guide highlights turtles and moray eels at this beginner-friendly site; sightings are not guaranteed.", reason: "Enjoy a shallow house reef suited to newer divers", level: "Beginner", preparation: ["Maximum depth listed by PADI: 12 metres."], source: { label: "PADI — Batu Nisan", url: "https://www.padi.com/dive-site/malaysia/batu-nisan-2/" } },
  { id: "perhentian-d-lagoon", backendDiveSiteId: 19, name: "D'Lagoon", island: "Perhentian", publicAreaLabel: "Perhentian Islands", position: [5.905, 102.735], introduction: "D'Lagoon is highlighted in PADI's Perhentian guide as a site for finding smaller reef animals and other critters.", habitat: "The site's sheltered reef habitat rewards slow, careful observation rather than covering distance quickly.", marineLife: "The PADI guide mentions critters, Jenkins whiprays and passing blacktip reef sharks; every sighting depends on the dive conditions.", reason: "Look closely for macro life and occasional larger visitors", level: "Beginner" },
  { id: "perhentian-shark-point", backendDiveSiteId: 18, name: "Shark Point", island: "Perhentian", publicAreaLabel: "Perhentian Islands", position: [5.91, 102.739], introduction: "Shark Point is a Perhentian reef site known for the chance to observe larger marine life.", habitat: "Open reef habitat provides viewing opportunities beyond the coral itself.", marineLife: "PADI highlights blacktip reef sharks, turtles, barracuda and batfish here, while making no individual sighting certain.", reason: "Watch for blacktip reef sharks and other passing marine life", level: "Intermediate" },
  { id: "perhentian-sugar-wreck", backendDiveSiteId: 14, name: "Sugar Wreck", island: "Perhentian", publicAreaLabel: "Perhentian Islands", position: [5.892, 102.703], introduction: "The Sugar Wreck is the cargo ship MV Union Star 17, now resting at a maximum depth of about 18 metres.", habitat: "The more than 90-metre wreck provides a large artificial structure to explore on a boat-entry ocean dive.", marineLife: "Marine life may gather around and shelter within the wreck, but sightings vary with conditions.", reason: "Explore one of the Perhentian Islands' best-known shallow wrecks", level: "Intermediate", preparation: ["Maximum depth listed by PADI: 18 metres.", "This is a wreck dive. Confirm current conditions, access limits and wreck-diving procedures with a licensed operator."], source: { label: "PADI — Sugar Wreck", url: "https://www.padi.com/dive-site/malaysia/sugar-wreck/" } },
  { id: "perhentian-tanjung-basi", backendDiveSiteId: 20, name: "Tanjung Basi", island: "Perhentian", publicAreaLabel: "Perhentian Islands", position: [5.897, 102.73], introduction: "Tanjung Basi is included by PADI among the Perhentian Islands' notable dive sites for its diversity.", habitat: "This profile intentionally avoids attaching an unverified species list or fixed conditions to the site.", marineLife: "Marine life and coral condition should be confirmed with a local licensed operator on the day of the dive.", reason: "Experience a locally recognised site noted for reef diversity", level: "Intermediate" },
  { id: "perhentian-temple-of-the-sea", backendDiveSiteId: 13, name: "Temple of the Sea (Tokong Laut)", island: "Perhentian", publicAreaLabel: "Perhentian Islands", position: [5.95912, 102.65972], introduction: "Temple of the Sea, also called Tokong Laut, is a boat-entry pinnacle dive with a maximum depth of about 25 metres.", habitat: "Towering pinnacles covered with corals and sponges create a colourful, structurally varied underwater landscape.", marineLife: "PADI lists schools of tropical fish, rays and bamboo sharks; whale sharks are described as rare visitors rather than an expected sighting.", reason: "Explore coral- and sponge-covered pinnacles with abundant reef life", level: "Experienced", preparation: ["Maximum depth listed by PADI: 25 metres.", "Suggested equipment listed by PADI: camera, dive computer, exposure protection, surface marker buoy and torch."], source: { label: "PADI — Temple of the Sea", url: "https://www.padi.com/dive-site/malaysia/temple-of-the-sea/" } },
  { id: "perhentian-terumbu-tiga", backendDiveSiteId: 16, name: "Terumbu Tiga", island: "Perhentian", publicAreaLabel: "Perhentian Islands", position: [5.888, 102.727], introduction: "Terumbu Tiga, also called T3 or Three Brothers, is named for the three large boulders that define the site.", habitat: "Small swim-throughs, soft and hard corals, rocky reef and rubble patches create varied terrain.", marineLife: "PADI highlights barracuda, reef and bamboo sharks, plus macro subjects such as nudibranchs, shrimp and pipefish; sightings vary.", reason: "Explore varied boulder topography with wide-angle and macro photography opportunities", level: "Intermediate" },
  { id: "perhentian-vietnamese-wreck", backendDiveSiteId: 15, name: "Vietnamese Wreck", island: "Perhentian", publicAreaLabel: "Perhentian Islands", position: [5.884, 102.71], introduction: "The Vietnamese Wreck is a small wreck sunk in the 1970s and resting at about 24 metres.", habitat: "Currents can sweep through the wreck and surrounding sand and soft-coral habitat, making it a more demanding dive.", marineLife: "PADI highlights nudibranchs, seahorses and blue-ringed octopus among the small animals found around the site; sightings vary.", reason: "Search carefully for unusual macro life around a historic wreck", level: "Experienced", preparation: ["Depth reported by PADI: about 24 metres.", "PADI notes that currents can make this a challenging site; confirm suitability with a licensed operator." ] },
  { id: "redang-mini-mount", backendDiveSiteId: 23, name: "Mini Mount", island: "Redang", publicAreaLabel: "Redang Island", position: [5.76, 103.017], introduction: "Mini Mount, also known as Chek Isa, is an underwater seamount near Redang and a locally promoted day and night dive.", habitat: "A compact underwater rise provides changing depth and reef structure around the mount.", marineLife: "Species and abundance vary by season, current and time of day; confirm current observations with a local operator.", reason: "Explore compact seamount topography by day or at night", level: "Intermediate" },
  { id: "redang-pulau-paku-besar", backendDiveSiteId: 21, name: "Pulau Paku Besar", island: "Redang", publicAreaLabel: "Redang Island", position: [5.7781, 103.0419], introduction: "Pulau Paku Besar is a small island near Redang reached by a short boat trip from the main resort area.", habitat: "Tourism material for Redang highlights the island's underwater scenery, while conditions remain changeable.", marineLife: "Fish and coral observations vary from dive to dive and should be checked with a local licensed operator.", reason: "Take in underwater scenery around one of Redang's small offshore islands", level: "Intermediate" },
  { id: "redang-tanjung-tengah", backendDiveSiteId: 22, name: "Tanjung Tengah", island: "Redang", publicAreaLabel: "Redang Island", position: [5.79, 103.025], introduction: "A named Redang headland site presented for coral and reef-fish observation.", habitat: "Corals, hydroids and fan-like growth illustrate the range of attached reef life.", marineLife: "Trevally and other mobile reef fish may pass over the reef without being guaranteed.", reason: "Attached reef life and passing fish", level: "Intermediate" },
  { id: "redang-terumbu-kili", backendDiveSiteId: 24, name: "Terumbu Kili", island: "Redang", publicAreaLabel: "Redang Island", position: [5.774, 103.052], introduction: "Terumbu Kili is a rocky outcrop off the southern end of Redang and is widely listed among the area's notable dive sites.", habitat: "The exposed rocky outcrop creates a different setting from Redang's sheltered house reefs.", marineLife: "Marine life and dive conditions depend on current and season; confirm the day's plan with a local licensed operator.", reason: "Explore a prominent offshore rocky reef", level: "Intermediate" },
  { id: "tioman-batu-malang", backendDiveSiteId: 8, name: "Batu Malang", island: "Tioman", publicAreaLabel: "Tioman Island", position: [2.91, 104.153], introduction: "Batu Malang is a relatively shallow reef formed by large granite boulders resting on one another.", habitat: "Boulder swim-throughs and rocky outcrops support both hard and soft coral growth.", marineLife: "PADI highlights colourful corals and nudibranchs at the site; sightings vary with conditions.", reason: "Explore intricate boulder topography and shallow coral scenery", level: "Intermediate", source: { label: "PADI — Batu Malang", url: "https://www.padi.com/dive-site/malaysia/batu-malang/" } },
  { id: "tioman-chebeh-island", backendDiveSiteId: 2, name: "Chebeh Island", island: "Tioman", publicAreaLabel: "Tioman Island", position: [2.933, 104.098], introduction: "Chebeh is a steeply sloping reef around a rocky granite island, with depth zones of hard and soft coral.", habitat: "Massive granite boulders carry gorgonians and black corals, with hard coral shallower and soft coral deeper on the slope.", marineLife: "PADI lists fusiliers, batfish, barracuda, reef sharks, jacks and trevallies among the site's possible sightings.", reason: "See dramatic granite formations, coral-covered slopes and passing pelagic fish", level: "Experienced", source: { label: "PADI — Chebeh Island", url: "https://www.padi.com/dive-site/malaysia/chebeh-island/" } },
  { id: "tioman-coral-island", backendDiveSiteId: 11, name: "Coral Island (Pulau Tulai)", island: "Tioman", publicAreaLabel: "Tioman Island", position: [2.9129, 104.1094], introduction: "Coral Island, or Pulau Tulai, is a well-known Tioman-area island that gives access to several reef dives.", habitat: "Granite rock, coral gardens and nearby sites such as Fan Canyon create varied underwater scenery.", marineLife: "Reef fish and invertebrates may shelter around coral and rock, with sightings dependent on conditions.", reason: "Visit a coral-garden setting shared by several recognised dive sites", level: "Beginner" },
  { id: "tioman-fan-canyon", backendDiveSiteId: 9, name: "Fan Canyon", island: "Tioman", publicAreaLabel: "Tioman Island", position: [2.925, 104.116], introduction: "Fan Canyon is a boat-entry reef on Coral Island that slopes to about 29 metres.", habitat: "Soft-coral-covered granite boulders form a canyon lined with gorgonian sea fans; PADI also notes a narrow tunnel at about 16 metres.", marineLife: "PADI highlights nudibranchs, flatworms, clownfish, scorpionfish, lionfish, hawksbill turtles and gorgonian fans.", reason: "Explore a sea-fan canyon with strong macro-photography potential", level: "Experienced", preparation: ["Maximum depth listed by PADI: 29 metres.", "PADI recommends Advanced Open Water training and lists a dive computer, surface marker buoy and torch among suggested equipment."], source: { label: "PADI — Fan Canyon", url: "https://www.padi.com/dive-site/malaysia/fan-canyon/" } },
  { id: "tioman-labas-island", backendDiveSiteId: 5, name: "Labas Island", island: "Tioman", publicAreaLabel: "Tioman Island", position: [2.886, 104.12], introduction: "Labas Island has two dive areas and is known for numerous swim-throughs, small caverns and coral gardens.", habitat: "A maze-like arrangement of rocks creates swim-throughs beside dense coral habitat.", marineLife: "Macro organisms including nudibranchs may be found around the coral gardens, but sightings vary.", reason: "Explore distinctive swim-throughs and coral gardens", level: "Experienced", preparation: ["PADI warns that some areas may require training and experience beyond basic certification. Stay within the limits of your training."], source: { label: "PADI — Labas Island", url: "https://www.padi.com/dive-site/malaysia/labas-island/" } },
  { id: "tioman-malang-rock", backendDiveSiteId: 6, name: "Malang Rock", island: "Tioman", publicAreaLabel: "Tioman Island", position: [2.904, 104.146], introduction: "A named Tioman rock site with plate, branching and mound-like coral forms.", habitat: "Plate and branching colonies create layered reef structure.", marineLife: "Small fish may use the spaces above and beneath plate corals.", reason: "Layered coral shapes around rocky relief", level: "Intermediate" },
  { id: "tioman-marine-park", backendDiveSiteId: 12, name: "Marine Park (Tekek)", island: "Tioman", publicAreaLabel: "Tioman Island", position: [2.8341, 104.1626], introduction: "A named site near Tekek presented for accessible reef education and responsible observation.", habitat: "Corals and smaller attached organisms demonstrate that reef life includes more than fish.", marineLife: "Marine worms, small fish and other invertebrates may be visible with careful observation.", reason: "Accessible reef learning and observation practice", level: "Beginner" },
  { id: "tioman-pirate-reef", backendDiveSiteId: 10, name: "Pirate Reef", island: "Tioman", publicAreaLabel: "Tioman Island", position: [2.86, 104.155], introduction: "Pirate Reef is described by a local PADI dive centre as a shallow, calm Tioman dive site.", habitat: "A relatively sheltered reef setting can provide a gentler dive when local conditions are suitable.", marineLife: "The exact animals present change with season and conditions; no sighting should be treated as guaranteed.", reason: "Enjoy a shallower, calmer reef experience", level: "Beginner", source: { label: "PADI — Berjaya Tioman Dive Centre", url: "https://www.padi.com/dive-center/malaysia/berjaya-tioman-dive-centre/" } },
  { id: "tioman-renggis", backendDiveSiteId: 3, name: "Renggis Island", island: "Tioman", publicAreaLabel: "Tioman Island", position: [2.8099, 104.1356], introduction: "Renggis is a small island with a fringing reef and shallow depths commonly used for beginner diving.", habitat: "The dive generally ranges from about 6 to 13 metres across an accessible fringing reef.", marineLife: "PADI highlights hawksbill turtles and blacktip reef sharks among common sightings, without guaranteeing an encounter.", reason: "Enjoy a shallow fringing reef suitable for newer divers", level: "Beginner", preparation: ["Depth range reported by PADI: about 6 to 13 metres."], source: { label: "PADI — Pulau Renggis", url: "https://www.padi.com/dive-site/malaysia/pulau-renggis/" } },
  { id: "tioman-sepoi-island", backendDiveSiteId: 7, name: "Sepoi Island", island: "Tioman", publicAreaLabel: "Tioman Island", position: [2.948, 104.105], introduction: "A named Tioman island site presented for coral, reef-fish and sea-fan observation.", habitat: "Coral cover and gorgonian sea fans create vertical and branching forms.", marineLife: "Small reef fish may gather around coral and fan structures.", reason: "Coral-and-fan scenery and reef photography", level: "Intermediate" },
  { id: "tioman-soyak-island", backendDiveSiteId: 4, name: "Soyak Island", island: "Tioman", publicAreaLabel: "Tioman Island", position: [2.827, 104.158], introduction: "Soyak is a shallow island reef with large boulders and a maximum reef depth of about 16 metres.", habitat: "Large boulders give the natural reef varied topography; nearby wrecks are separate, deeper attractions connected by lines.", marineLife: "Schools of juvenile fish, nudibranchs and bottom-dwelling species may be found around the reef and nearby wreck habitat.", reason: "Explore a shallow boulder reef with varied marine life", level: "Beginner", preparation: ["The natural reef is reported at about 16 metres maximum; nearby wrecks can be substantially deeper."], source: { label: "PADI — Soyak Island", url: "https://www.padi.com/dive-site/malaysia/soyak-island/" } },
  { id: "tioman-tiger-reef", backendDiveSiteId: 1, name: "Tiger Reef", island: "Tioman", publicAreaLabel: "Tioman Island", position: [2.965, 104.12], introduction: "Tiger Reef is a submerged pinnacle between Labas and Sepoi, with an average depth around 15 metres and a listed maximum of 24 metres.", habitat: "The pinnacle's rock formations are covered by soft and hard corals and barrel sponges; currents can be strong in the channel.", marineLife: "Current can attract schools of jacks, mackerel, barracuda, fusiliers and rainbow runners, while reef animals shelter around boulders and ledges.", reason: "Experience colourful pinnacle scenery and schooling fish in moving water", level: "Experienced", preparation: ["Maximum depth listed by PADI: 24 metres.", "PADI recommends Advanced Open Water training; confirm current strength and suitability with a licensed operator."], source: { label: "PADI — Tiger Reef", url: "https://www.padi.com/dive-site/malaysia/tiger-reef-2/" } },
];

export const reefSites: ReefSite[] = profileSpecs.map((site) => ({
  ...site,
  images: imagesFor(site.id),
  reefFeatures: [
    { title: "Site character", description: site.habitat },
    { title: "Conditions vary", description: "This visitor profile is not a live site-condition report. Check current conditions with a licensed operator." },
  ],
  marineLife: [site.marineLife, "Wildlife and coral condition vary by season and dive; no sighting is guaranteed."],
  popularReasons: [site.reason],
  experience: { level: site.level, explanation: `${site.level} is a general planning indicator only. A licensed operator must assess current conditions and individual suitability.` },
  preparation: [...(site.preparation ?? []), ...commonPreparation],
  source: site.source ?? sources[site.island],
}));

export const reefIslands = ["Perhentian", "Redang", "Tioman"] as const;
